name = input('Enter your name = ')
college = input('Enter your college = ')
age = input('Enter your age = ')
city = input('Enter your city = ')
print(name, type(name))
print(college, type(college))
print(age, type(age))
print(city, type(city))